# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-dev tcl-dev tk-dev fontconfig libfontconfig1 libfontconfig1-dev cmake cmake-data extra-cmake-modules build-essential xvfb 
          python -m pip install scikit-build
          python -m pip install tkextrafont

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-dotenv
          python -m pip install .

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          pytest
