# This workflow will install Python dependencies, pyinstaller and build executable with a version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: "Nuitka builds (windows)"
on:
  push:
    branches: [ "main", "nuitka-test" ]
  pull_request:
    branches: [ "main", "nuitka-test" ]

jobs:
  build:

    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Nuitka

      - name: nuitka build
        run: echo Yes| python -m nuitka --include-data-dir=biscuit\\res=res --include-package-data=tkextrafont --include-package-data=sv_ttk --include-package-data=pygments --include-package-data=tkinterweb --include-package-data=mistune --follow-import-to=pygments --follow-import-to=tkextrafont --follow-import-to=mistune --follow-import-to=tkinterweb --include-package=tkextrafont --include-package=pygments --include-package=mistune --include-package=tkinterweb --include-module=pygments --include-module=mistune --include-module=tkinterweb --include-module=tkextrafont --follow-imports --standalone --enable-plugin=tk-inter biscuit

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
            name: "biscuit-nightly"
            path: "biscuit.dist"
